name: Release

# 触发器
on:
  push:
    branches:
      - rel

jobs:
  read_me_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/checkout@v2
        with:
          repository: qiushui95/GithubActionShell
          path: "sh"
      - name: 设置ReadMe旧版本环境变量
        run: bash ./sh/env_version.sh library/gradle.properties VERSION_OLD
      - name: 更新打包版本
        run: bash ./sh/update_version.sh library/gradle.properties
      - name: 设置版本环境变量
        run: bash ./sh/env_version.sh library/gradle.properties VERSION_CUR
      - name: 更新ReadMe
        run: sed -i 's/${{env.VERSION_OLD}}/${{env.VERSION_CUR}}/g' README.md
      - name: 配置git
        run: bash ./sh/git_config.sh
      - name: 提交ReadMe更新记录
        run: |
          git add README.md
          git library/gradle.properties
          git commit -m "更新版本号"
          git tag ${{env.VERSION_CUR}}
          git push origin rel:master
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{env.VERSION_CUR}}
          release_name: Release ${{env.VERSION_CUR}}
          draft: false
          prerelease: false