name: Release

# 触发器
on:
  push:
    branches:
      - master

jobs:
  read_me_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: qiushui95/GithubActionShell
          path: "sh"
      - name: 设置版本环境变量
        run: bash ./sh/env_version.sh library/gradle.properties VERSION_CUR
      - name: 设置ReadMe旧版本环境变量
        run: bash ./sh/env_version.sh README.md VERSION_OLD
      - name: 更新ReadMe
        run: sed -i 's/${{env.VERSION_OLD}}/${{env.VERSION_CUR}}/g' README.md
      - name: 提交ReadMe更新记录
        uses: EndBug/add-and-commit@v7.5.0
        with:
          add: "README.md"
          author_name: "YCX-Github"
          author_email: "ycx974577817@gmail.com"
          message: "更新ReadMe版本号"
          tag: ${{env.VERSION_CUR}}
          push: true
  release:
    runs-on: ubuntu-latest
    needs:
      - read_me_version
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - uses: actions/checkout@v2
        with:
          repository: qiushui95/GithubActionShell
          path: "sh"
      - name: 设置版本环境变量
        run: bash ./sh/env_version.sh library/gradle.properties VERSION_CUR
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{env.VERSION_CUR}}
          release_name: Release ${{env.VERSION_CUR}}
          draft: false
          prerelease: false
  update_next_version:
    needs:
      - release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - uses: actions/checkout@v2
        with:
          repository: qiushui95/GithubActionShell
          path: "sh"
      - name: 更新打包版本
        run: bash ./sh/update_version.sh library/gradle.properties
      - name: 设置版本环境变量
        run: bash ./sh/env_version.sh library/gradle.properties LIB_VERSION
      - name: 提交版本修改记录
        uses: EndBug/add-and-commit@v7.5.0
        with:
          add: "."
          author_name: "YCX-Github"
          author_email: "ycx974577817@gmail.com"
          message: "更新下次发布版本为${{env.LIB_VERSION}}"
          push: true